config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, except: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :sub,
    foreign_key: :sub_id,
    primary_key: :id,
    class_name: :Sub

  belongs_to :author,
    foreign_key: :author_id,
    primary_key: :id,
    class_name: :User
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    primary_key: :id,
    class_name: :User

  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  before_validation :ensure_session_token
  attr_reader :password

  has_many :subs
  has_many :posts

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
    post = Post.new(post_params)
    post.author_id = current_user.id
    post.sub_id = params[:sub_id]

    if post.save
      redirect_to sub_url(post.sub_id)
    else
      flash[:errors] = post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = current_user.posts.find(params[:id])

    if post.update_attributes(post_params)
      redirect_to sub_post_url(post)
    else
      flash[:errors] = post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  # params = { id => 1, title => dfg}
  # input type = text name="title"
  #
  # params = { id: 1 , user = {username: "tom"}}
  # params[:user][:username]
  # name = "user[username]"
  #
  # name = "username"
  # params[:username]
  # params = { id: 1 , username: "tom"}

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy
    redirect_to sub_url(post.sub_id)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user
      login!(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Invalid Credentials']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
  end

  def new
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def create
    sub = Sub.new(sub_params)
    debugger
    sub.moderator_id = current_user.id
    if sub.save
      redirect_to sub_url(sub)
    else
      flash[:errors] = sub.errors.full_messages
      render :new
    end
  end

  def update
    sub = Sub.find(params[:id])
    if sub.update_attributes(sub_params)
      redirect_to sub_url(sub)
    else
      flash[:errors] = sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    '<input type="hidden"
     name="authenticity_token"
     value="<%= form_authenticity_token %>">'.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/edit.html.erb
<h2>Edit Sub</h2>

<form class="" action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <br>

  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <br>
  <input type="submit" name="" value="Update Sub">
</form>

app/views/subs/index.html.erb
<h1>SUB INDEX</h1>

<ul>
  <% @subs.each do |sub| %>
    <li>
      <a href="<%=sub_url(sub)%>"><%= sub.title %></a>
    </li>
  <% end %>
</ul>

<a href="<%= new_sub_url %>">Make new sub</a>

app/views/subs/new.html.erb
<h2>New Sub</h2>

<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token_input %>
  <label>
    Title
    <input type="text" name="sub[title]" value="">
  </label>

  <br>

  <label>
    Description
    <input type="text" name="sub[description]" value="">
  </label>
  <br>
  <input type="submit" name="" value="Create New Sub">
</form>

app/views/users/new.html.erb
<h1>Sign In</h1>

<form action="<%= users_url  %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
      Username
      <input type="text" name="user[username]" value="">
    </label>

    <br>

    <label>
      Password
      <input type="text" name="user[password]" value="">
    </label>

    <input type="submit" name="" value="Moist me">
</form>